### ISSUE TITLE
这个包可以提供一下吗

### ISSUE THREAD

**Issue by nobody2014100** [ameizi/spring-boot-apollo-sample#1]
<dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-client</artifactId>
            <version>0.8.0</version>
        </dependency>

**Comment by v5tech** [comment]
这个是 apollo自带的啊，在maven中央仓库就有啊 @klaus20141002

**Comment by nobody2014100** [comment]
https://github.com/ctripcorp/apollo.git , 后来找到这个应该可以用吧。
