### ISSUE TITLE
报错 错误: 找不到或无法加载主类 net.ameizi.SpringBootApolloSampleApplication

### ISSUE THREAD

**Issue by xuezhongyu01** [ameizi/spring-boot-apollo-sample#2]
按照项目代码搭建，报 错误: 找不到或无法加载主类 net.ameizi.SpringBootApolloSampleApplication

**Comment by v5tech** [comment]
@xuezhongyu01 请问你是怎么运行的？怎么会报这个类错误？你需要手动打包apollo-client依赖jar文件，然后在项目中引入你自己构建好的apollo-client.jar文件，因为早期apollo服务器的信息是在构建的时候打进jar文件里面去的。至于你提到的这个错误，请你拉取最新的代码，然后重新构建在idea或命令行进行构建，我在我本地构建了运行了，没有复现你提到的这个错误
